spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${AUTH_DB_NAME}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
